apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: auth-api
  description: User login
spec:
  type: openapi
  lifecycle: production
  owner: group:dev-team
  system: acn-dev-portal
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Auth API
      description: API to login an user
      license:
        name: MIT
    servers:
      - url: http://auth.example.com/v1
    paths:
      /login:
        post:
          summary: Simulate user login
          description: Accepts user credentials and returns a login token.
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    username:
                      type: string
                      description: The username of the user
                    password:
                      type: string
                      description: The password of the user
          responses:
            '200':
              description: Login successful, returns an authentication token.
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      token:
                        type: string
                        description: Authentication token
            '401':
              description: Unauthorized, invalid username or password.
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      error:
                        type: string
                        description: Error message for invalid credentials
