apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo
  description: A simple Spring Boot application
  annotations:
    backstage.io/techdocs-ref: dir.
spec:
  type: service
  lifecycle: production
  owner: user:dagasp10
  system: acn-dev-portal
  dependsOn: []
  providesApis:
    - artist-api
  subcomponentOf: []
links:
  - type: catalog
    url: ./apis/artist-api/catalog-info.yaml
  - type: catalog
    url: ./system.yaml
