apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example
  description: example.com
  annotations:
    backstage.io/kubernetes-id: backstage
spec:
  type: website
  lifecycle: production
  owner: user:guest
