apiVersion: backstage.io/v1beta1
kind: Component
metadata:
  name: my-service
  annotations:
    # Aggiungi l'annotazione per il plugin Kubernetes
    kubernetes.io/cluster-name: kind-kind # Specifica il cluster
spec:
  type: service
  lifecycle: production
  owner: team-a
