site_name: 'Example Documentation'
repo_url: https://github.com/dagasp/springboot-test
edit_uri: https://github.com/dagasp/springboot-test/blob/master/docs/index.md

nav:
  - Home: index.md

plugins:
  - techdocs-core